version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install cmake and make"
          shell: powershell.exe
          command: |
            choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"'
            choco install make
      - run:
          name: "Build koinos chain"
          shell: powershell.exe
          command: |
            mkdir build
            cd build
            cmake --build .. --config Release