version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install cmake"
          shell: powershell.exe
          command: |
            choco install cmake --pre
      - run:
          name: "Build koinos chain"
          shell: powershell.exe
          command: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j