name: CMake Build Matrix

on: [push, pull_request]

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: build
      run: |
        apt-get update && export UBUNTU_FRONTEND=noninteractive
        apt-get -y install --no-install-recommends  \
        gcc \
        g++ \
        ccache \
        musl-dev \
        linux-headers-amd64 \
        libgmp-dev \
        cmake \
        make \
        git \
        perl \
        python3 \
        python3-pip \
        python3-setuptools && \
        pip3 install --user dataclasses_json Jinja2 importlib_resources pluginbase gitpython
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j       

