name: CMake Build Matrix

on: [push, pull_request]

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: build
      run: |
        apt install build-essentials libgmp cmake
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j       

