name: CMake Build Matrix

env:
  CTEST_NO_TESTS_ACTION: error
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on: [push, pull_request]

jobs:

  core:

    strategy:
      matrix:
        os: [ubuntu-latest]
        shared: [true]

    runs-on: ${{ matrix.os }}

    steps:

   - uses: actions/checkout@v3

    - name: config
      run: >-
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..        

    - name: build
      run: make -j
